### ISSUE TITLE
Some questions on implementing the atcab_read_enc function

### ISSUE THREAD

**Issue by chrisb2** [dmazzella/ucryptoauthlib#3]
I have started trying to implement the atcab_read_enc() function. 

This function relies on the atcab_gendig() function which I notice in code appears to be implemented, but the readme does not have a tick next to it. What is the current state of the atcab_gendig() function?

I am using as a guide the datasheets including "Atmel CryptoAuthentication Encrypted Reads and Writes" and the Atmel C++ library, but just wonder if you have any advise for me?

thanks,
Chris

**Comment by dmazzella** [comment]
Hi Chris,
the function [atcab_gendig](https://github.com/dmazzella/ucryptoauthlib/blob/2cd72b83ec02280683887ddd31a7e9d40568d76c/modules/cryptoauthlib/basic.py#L135) is currently not implemented

If you want to implement it I can suggest you to see the microchip's implementation [calib_gendig](https://github.com/MicrochipTech/cryptoauthlib/blob/1cb00def6dba72e82465a5a8584e7f2a98195e24/lib/calib/calib_gendig.c#L49) and [atGenDig](https://github.com/MicrochipTech/cryptoauthlib/blob/1cb00def6dba72e82465a5a8584e7f2a98195e24/lib/calib/calib_command.c#L110).

Regards,
D.

**Comment by dmazzella** [comment]
Hi Chris,
if you have working code and you want to submit PR you are welcome.

Thanks,
D.
