### ISSUE TITLE
RP2 ARDUINO_NANO_RP2040_CONNECT

### ISSUE THREAD

**Issue by mattmeye** [dmazzella/ucryptoauthlib#5]
Hello Damiano,

i tried to compile your lib for RP2 ARDUINO_NANO_RP2040_CONNECT. 
These are my commands:

```
$ git clone https://github.com/micropython/micropython.git
$ cd micropython
micropython$ git submodule update --init
micropython$ git clone https://github.com/dmazzella/ucryptoauthlib.git micropython-lib/ucryptoauthlib
micropython$ make -C mpy-cross && make -C ports/rp2 BOARD=ARDUINO_NANO_RP2040_CONNECT FROZEN_MANIFEST="$(pwd)/micropython-lib/ucryptoauthlib/manifest.py""
```
After flashing the rp2040 with the uf2 image, and the following command: 

```from cryptoauthlib.device import ATECCX08A
device = ATECCX08A()
```

i got this error 

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cryptoauthlib/device.py", line 30, in __init__
NoDevicesFoundError: For protocols that support device discovery (kit protocol), no devices were
found
```

Do you have an idea how I can fix the device detection for the arduino rp2040 https://docs.arduino.cc/hardware/nano-rp2040-connect ?

Kind regards,
Matt

**Comment by dmazzella** [comment]
Hi Matthias,
[device.py:24](https://github.com/dmazzella/ucryptoauthlib/blob/254844f3bb2fbcb1c1ba393c540e6b79ea572e72/modules/cryptoauthlib/device.py#L24) use `bus=machine.I2C(1, freq=133000)` for scan of all i2c devices connected.

Have you tried to see what devices are listed on i2c bus?  
Try `machine.I2C(1, freq=133000).scan()`

At [device.py:18](https://github.com/dmazzella/ucryptoauthlib/blob/254844f3bb2fbcb1c1ba393c540e6b79ea572e72/modules/cryptoauthlib/device.py#L18) you can see the addresses to search `{0x50: "ATECC508A", 0x60: "ATECC608A"}`

Kind regards,
D.

**Comment by mattmeye** [comment]
Hello Damiano,

Here are the results:
With the image above: `machine` could not be found => therefore the cmd fails.
With the official micropython image, the result with your command is empty `[]` but i checked the docs again ( https://docs.micropython.org/en/latest/library/machine.I2C.html and https://docs.arduino.cc/tutorials/nano-rp2040-connect/rp2040-python-api#i2c )
and I get a good result with `I2C(0, scl=Pin(13), sda=Pin(12), freq=100_000).scan()` => 
`[96, 106]`

So i have to find out, what is wrong with my custom image. I will come back to you as soon as i have results.
Thanks a lot.

Matt

**Comment by dmazzella** [comment]
Hi Matthias,
you can use `I2C(0, scl=Pin(13), sda=Pin(12), freq=100_000)` as `bus` kwargs of [ATECCX08A()](https://github.com/dmazzella/ucryptoauthlib/blob/254844f3bb2fbcb1c1ba393c540e6b79ea572e72/modules/cryptoauthlib/device.py#L24)

like: 

```python
ATECCX08A(bus=I2C(0, scl=Pin(13), sda=Pin(12), freq=100_000))
```

D.

**Comment by mattmeye** [comment]
Hi Damiano,

thank you for support. I am able to init the device and can execute ~.info().
